apiVersion: v1
kind: Service
metadata:
  name: web-server-service
  namespace: production
spec:
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  selector:
    app: vois-app
  type: NodePort